export const TEST = 'common/TEST'

// common
export const GET_MY_INFO = 'common/GET_MY_INFO'
export const POST_MY_INFO = 'common/POST_MY_INFO'
export const USER_LOGIN_SET = 'common/USER_LOGIN_SET'
export const SET_ACTIVE_MODAL = 'common/SET_ACTIVE_MODAL'
export const GET_LANG_DATA = 'common/GET_LANG/DATA'
export const SET_INFO_BY_LANG = 'common/SET_INFO_BY_LANG'
export const SET_SHOW_TOP = 'common/SET_SHOW_TOP'
export const TOGGLE_FULL_PIVOT = 'common/TOGGLE_FULL_PIVOT'

// glossary
export const GET_GLOSSARY_INIT_CODES = 'glossary/GET_GLOSSARY_INIT_CODES'
export const GET_GLOSSARY_LIST = 'glossary/GET_GLOSSARY_LIST'
export const GET_GLOSSARY = 'glossary/GET_GLOSSARY'

// notice
export const GET_NOTICE_INIT = 'notice/GET_NOTICE_INIT'
export const GET_NOTICE_LIST = 'notice/GET_NOTICE_LIST'
export const GET_NOTICE = 'notice/GET_NOTICE'
export const GET_NOTICE_URGENCY = 'notice/GET_NOTICE_URGENCY'
export const SET_NOTICE_VISIBILITY = 'notice/SET_NOTICE_VISIBILITY'

// project
export const GET_PROJECT_LIST = 'project/GET_PROJECT_LIST'
export const POST_PROJECT_FAVORITE = 'project/POST_PROJECT_FAVORITE'
export const DELETE_PROJECT_FAVORITE = 'project/DELETE_PROJECT_FAVORITE'
export const GET_PROJECT_INIT = 'project/GET_PROJECT_INIT'

// menu
export const GET_MENU_LIST = 'menu/GET_MENU_LIST'
export const SET_ACTIVE_MENU = 'menu/SET_ACTIVE_MENU'
export const GET_TWO_DEPTH_MENU_INFO = 'menu/GET_TWO_DEPTH_MENU_INFO'
export const INIT_MENU_LIST = 'menu/INIT_MENU_LIST'
export const TOGGLE_LEFT_MENU = 'menu/TOGGLE_LEFT_MENU'
export const TRANSITION_END = 'menu/TRANSITION_END'

// report
export const INIT_REPORT_INFO = 'report/INIT_REPORT_INFO'
export const INIT_PREVIEW_INFO = 'report/INIT_PREVIEW_INFO'
export const PROJECT_MENU = 'report/PROJECT_MENU'
export const UPDATE_CHART_DATA = 'report/UPDATE_CHART_DATA'
export const UPDATE_PIVOT_DATA = 'report/UPDATE_PIVOT_DATA'
export const UPDATE_TABLE_DATA = 'report/UPDATE_TABLE_DATA'
export const UPDATE_OBJECT = '/report/UPDATE_OBJECT'
export const TOGGLE_RIGHT_PANEL = '/report/TOGGLE_RIGHT_PANEL'
export const CHECK_RIGHT_PANNEL = '/report/CHECK_RIGHT_PANNEL'
export const INIT_PIVOT_PANEL_INFO = '/report/INIT_PIVOT_PANEL_INFO'
export const UPDATE_CHART_DATA_LIST = '/report/UPDATE_CHART_DATA_LIST'
export const GET_ABOUT_THIS_REPORT = '/report/GET_ABOUT_THIS_REPORT'
export const GET_ABOUT_THIS_CHART = '/report/GET_ABOUT_THIS_CHART'
export const INIT_ABOUT_THIS_REPORT = '/report/INIT_ABOUT_THIS_REPORT'
export const INIT_ABOUT_THIS_CHART = '/report/INIT_ABOUT_THIS_CHART'
export const RIGHT_PANNEL_DEPTH = 'report/RIGHT_PANNEL_DEPTH'
export const SELECT_PIVOT_PANEL_INFO = 'report/SELECT_PIVOT_PANEL_INFO'

// chart
export const MAKE_LINE_CHART = 'chart/MAKE_LINE_CHART'
export const MAKE_COLUMN_CHART = 'chart/MAKE_COLUMN_CHART'
export const MAKE_STACKED_COLUMN_CHART = 'chart/MAKE_STACKED_COLUMN_CHART'
export const MAKE_AREA_CHART = 'chart/MAKE_AREA_CHART'
export const MAKE_PIE_CHART = 'chart/MAKE_PIE_CHART'
export const MAKE_GAUGE_CHART = 'chart/MAKE_GAUGE_CHART'
export const DOWNLOAD_CSV = 'pivot/DOWNLOAD_CSV'
export const DOWNLOAD_EXCEL = 'pivot/DOWNLOAD_EXCEL'
export const UPDATE_HALF_CHART_DATA = 'chart/UPDATE_HALF_CHART_DATA'
export const RIGHT_PANNEL_OBJECT_ID = 'chart/RIGHT_PANNEL_OBJECT_ID'
export const MAKE_BAR_CHART = 'chart/MAKE_BAR_CHART'
export const MAKE_STACKED_BAR_CHART = 'chart/MAKE_STACKED_BAR_CHART'
export const SET_CURRENT_DATES = 'chart/SET_CURRENT_DATES'
export const INIT_COLOR_CNT = 'chart/INIT_COLOR_CNT'
export const TOGGLE_UPDATE_GRID = 'chart/TOGGLE_UPDATE_GRID'
export const SET_PIVOT_IDX = 'chart/SET_PIVOT_IDX'
export const MAKE_TREEMAP_CHART = 'chart/MAKE_TREEMAP_CHART'
export const MAKE_STACKED_PERCENTAGE_BAR_CHART = 'chart/MAKE_STACKED_PERCENTAGE_BAR_CHART'
export const MAKE_STACKED_PERCENTAGE_COLUMN_CHART = 'chart/MAKE_STACKED_PERCENTAGE_COLUMN_CHART'
export const MAKE_GROUP_BAR_CHART = 'chart/MAKE_GROUP_BAR_CHART'
export const UPDATE_DOUBLE_HALF_CHART_DATA = 'chart/UPDATE_DOUBLE_HALF_CHART_DATA'

// dashboard
export const DASHBOARD = 'dashboard'
export const SET_DASHBOARD = 'dashboard/SET_DASHBOARD'
export const SET_DASHBOARD_STATE = 'chart/SET_DASHBOARD_STATE'
export const SET_DASHBOARD_CURRENT_DATES = 'chart/SET_DASHBOARD_CURRENT_DATES'
export const GET_BASIC_INFO_DATA = 'dashboard/GET_BASIC_INFO_DATA'
export const GET_CHART_DATA = 'dashboard/GET_CHART_DATA'
export const GET_WORLD_MAP_DATA = 'dashboard/GET_WORLD_MAP_DATA'
export const GET_REALTIME_LIVE_DATA = 'dashboard/GET_REALTIME_LIVE_DATA'
export const GET_REALTIME_TABLE_DATA = 'dashboard/GET_REALTIME_TABLE_DATA'
export const GET_REALTIME_PROJECT_INFO = 'dashboard/GET_REALTIME_PROJECT_INFO'
export const GET_REALTIME_OBJECT_IDS = 'dashboard/GET_REALTIME_OBJECT_IDS'
export const GET_DASHBOARD_GROSSARY_INFO = 'dashboard/GET_DASHBOARD_GROSSARY_INFO'

export const RESIZE_WINDOW = 'report/resizeWindow'
export const GET_DOWNLOAD_REPORT = 'dashboard/GET_DOWNLOAD_REPORT'
export const INIT_PIVOT_LIST = 'report/INIT_PIVOT_LIST'
export const CHANGE_DIMENSION = 'report/CHANGE_DIMENSION'
export const SET_HANDLER_FILTER_LIST = 'report/SET_HANDLER_FILTER_LIST'
